spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring-homework
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true
